Инициализация и настройка проекта
Wisher-Developers/wisher-backend pull request #1
Opened 2024-10-25 21:03 UTC by thepriceless

- Dockerfile для сборки приложения
- docker-compose для сборки мультиконтейнерного модуля
- необходимые минимально зависимости в build.gradle
- скрипты для создания базы
- настройка liquibase для миграций
- кафка и зукипер пока не настроены никак, настроим ближе к делу
- на примере одной сущности создал полный пакет-пример в соответствии с гексагональной архитектурой
- пример юнит теста
- пример kdoc

2024-10-25 21:18 UTC, goosescout requested changes
В .kt и .xml файлов нет пустых строк в конце.
Ты можешь настроить линтер/ide, чтобы эта строка добавлялась по умолчанию

2024-10-25 21:52 UTC, thepriceless commented
> В .kt и .xml файлах нет пустых строк в конце. Ты можешь настроить линтер/ide, чтобы эта строка добавлялась по умолчанию

Щас ktlint настрою и даже конфиг запушу, чтоб у всез одинаковый код-стайл был

2024-10-26 15:23 UTC, GarnetAki approved these changes

2024-10-27 15:48 UTC, goosescout approved these changes

2024-10-30 20:27 UTC, merged